cases = [
    {
        "id": 0,
        "idColor": 1,
        "imgName": "start",
        "type": "other",
        "name": "Case depart",
    },
    {
        "id": 1,
        "idProperty": 0,
        "idFamily": 0,
        "idColor": 0,
        "type": "property",
        "name": "boulevard de belleville",
        "rent": 2,
        "house_1": 10,
        "house_2": 30,
        "house_3": 90,
        "house_4": 160,
        "hotel": 250,
        "hypo": 30,
        "price": 60,
        "price_house": 50,
        "membership": [0, 1],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 2,
        "idColor": 9,
        "name": "Caisse de communaute",
        "imgName": "communityChest",
        "type": "communityChest",
    },
    {
        "id": 3,
        "idProperty": 1,
        "idFamily": 0,
        "idColor": 0,
        "type": "property",
        "name": "Rue Lecourbe",
        "rent": 4,
        "house_1": 20,
        "house_2": 60,
        "house_3": 180,
        "house_4": 320,
        "hotel": 450,
        "hypo": 30,
        "price": 60,
        "price_house": 50,
        "membership": [0, 1],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 4,
        "idColor": 9,
        "name": "impot sur le revenu",
        "imgName": "impot",
        "type": "tax",
        "price": 200,
    },
    {
        "id": 5,
        "idProperty": 22,
        "idFamily": 8,
        "idColor": 8,
        "imgName": "station",
        "type": "station",
        "name": "Gare Montparnasse",
        "rent": 50,
        "hypo": 100,
        "price": 200,
        "membership": [22, 23, 24, 25],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 6,
        "idProperty": 2,
        "idFamily": 1,
        "idColor": 1,
        "type": "property",
        "name": "Rue Vaugirard",
        "rent": 6,
        "house_1": 30,
        "house_2": 90,
        "house_3": 270,
        "house_4": 400,
        "hotel": 550,
        "hypo": 50,
        "price": 100,
        "price_house": 50,
        "membership": [2, 3, 4],
        "owned": False,
        "mortgaged": False,
    },
    {"id": 7, "idColor": 9, "name": "Chance", "imgName": "chance", "type": "chance",},
    {
        "id": 8,
        "idProperty": 3,
        "idFamily": 1,
        "idColor": 1,
        "type": "property",
        "name": "Rue de Courcelles",
        "rent": 6,
        "house_1": 30,
        "house_2": 90,
        "house_3": 270,
        "house_4": 400,
        "hotel": 550,
        "hypo": 50,
        "price": 100,
        "price_house": 50,
        "membership": [2, 3, 4],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 9,
        "idProperty": 4,
        "idFamily": 1,
        "idColor": 1,
        "type": "property",
        "name": "Avenue de la République",
        "rent": 8,
        "house_1": 40,
        "house_2": 100,
        "house_3": 300,
        "house_4": 450,
        "hotel": 600,
        "hypo": 60,
        "price": 120,
        "price_house": 50,
        "membership": [2, 3, 4],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 10,
        "idColor": 9,
        "name": "Simple Visite",
        "imgName": "inJail",
        "type": "other",
    },
    {
        "id": 11,
        "idProperty": 5,
        "idFamily": 2,
        "idColor": 2,
        "type": "property",
        "name": "Boulevard de la Villette",
        "rent": 10,
        "house_1": 50,
        "house_2": 150,
        "house_3": 450,
        "house_4": 625,
        "hotel": 750,
        "hypo": 70,
        "price": 140,
        "price_house": 100,
        "membership": [5, 6, 7],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 12,
        "idProperty": 26,
        "idFamily": 9,
        "idColor": 8,
        "type": "company",
        "imgName": "electricity",
        "name": "Compagnie de distribution d'electricité",
        "rent": 4,
        "hypo": 75,
        "price": 150,
        "membership": [26, 27],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 13,
        "idProperty": 6,
        "idFamily": 2,
        "idColor": 2,
        "type": "property",
        "name": "Avenue de Neuilly",
        "rent": 10,
        "house_1": 50,
        "house_2": 150,
        "house_3": 450,
        "house_4": 625,
        "hotel": 750,
        "hypo": 70,
        "price": 140,
        "price_house": 100,
        "membership": [5, 6, 7],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 14,
        "idProperty": 7,
        "idFamily": 2,
        "idColor": 2,
        "type": "property",
        "name": "Rue de Paradis",
        "rent": 12,
        "house_1": 60,
        "house_2": 180,
        "house_3": 500,
        "house_4": 700,
        "hotel": 900,
        "hypo": 80,
        "price": 160,
        "price_house": 100,
        "membership": [5, 6, 7],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 15,
        "idProperty": 23,
        "idFamily": 8,
        "idColor": 8,
        "type": "station",
        "imgName": "station",
        "name": "Gare de Lyon",
        "rent": 50,
        "hypo": 100,
        "price": 200,
        "membership": [22, 23, 24, 25],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 16,
        "idProperty": 8,
        "idFamily": 3,
        "idColor": 3,
        "type": "property",
        "name": "Avenue Mozart",
        "rent": 14,
        "house_1": 70,
        "house_2": 200,
        "house_3": 550,
        "house_4": 750,
        "hotel": 950,
        "hypo": 90,
        "price": 180,
        "price_house": 100,
        "membership": [8, 9, 10],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 17,
        "idColor": 9,
        "name": "Caisse de communaute",
        "imgName": "communityChest",
        "type": "communityChest",
    },
    {
        "id": 18,
        "idProperty": 9,
        "idFamily": 3,
        "idColor": 3,
        "type": "property",
        "name": "Boulevard Saint-Michel",
        "rent": 14,
        "house_1": 70,
        "house_2": 200,
        "house_3": 550,
        "house_4": 750,
        "hotel": 950,
        "hypo": 90,
        "price": 180,
        "price_house": 100,
        "membership": [8, 9, 10],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 19,
        "idProperty": 10,
        "idFamily": 3,
        "idColor": 3,
        "type": "property",
        "name": "Place Pigalle",
        "rent": 16,
        "house_1": 80,
        "house_2": 220,
        "house_3": 600,
        "house_4": 800,
        "hotel": 1000,
        "hypo": 100,
        "price": 200,
        "membership": [8, 9, 10],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 20,
        "idColor": 9,
        "imgName": "freeParking",
        "type": "other",
        "name": "Parc gratuit",
    },
    {
        "id": 21,
        "idProperty": 11,
        "idFamily": 4,
        "idColor": 4,
        "type": "property",
        "name": "Avenue Matignon",
        "rent": 18,
        "house_1": 90,
        "house_2": 250,
        "house_3": 700,
        "house_4": 875,
        "hotel": 1050,
        "hypo": 110,
        "price": 220,
        "price_house": 150,
        "membership": [11, 12, 13],
        "owned": False,
        "mortgaged": False,
    },
    {"id": 22, "idColor": 9, "name": "Chance", "imgName": "chance", "type": "chance",},
    {
        "id": 23,
        "idProperty": 12,
        "idFamily": 4,
        "idColor": 4,
        "type": "property",
        "name": "Boulevard Malesherbes",
        "rent": 18,
        "house_1": 90,
        "house_2": 250,
        "house_3": 700,
        "house_4": 875,
        "hotel": 1050,
        "hypo": 110,
        "price": 220,
        "price_house": 150,
        "membership": [11, 12, 13],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 24,
        "idProperty": 13,
        "idFamily": 4,
        "idColor": 4,
        "type": "property",
        "name": "Avenue Henri-Martin",
        "rent": 20,
        "house_1": 100,
        "house_2": 300,
        "house_3": 750,
        "house_4": 925,
        "hotel": 1100,
        "hypo": 120,
        "price": 240,
        "price_house": 150,
        "membership": [11, 12, 13],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 25,
        "idProperty": 24,
        "idFamily": 8,
        "idColor": 8,
        "type": "station",
        "name": "Gare du Nord",
        "imgName": "station",
        "rent": 50,
        "hypo": 100,
        "price": 200,
        "membership": [22, 23, 24, 25],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 26,
        "idProperty": 14,
        "idFamily": 5,
        "idColor": 5,
        "type": "property",
        "name": "Faubourg Saint-Honoré",
        "rent": 22,
        "house_1": 110,
        "house_2": 330,
        "house_3": 800,
        "house_4": 975,
        "hotel": 1150,
        "hypo": 130,
        "price": 260,
        "price_house": 150,
        "membership": [14, 15, 16],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 27,
        "idProperty": 15,
        "idFamily": 5,
        "idColor": 5,
        "type": "property",
        "name": "Place de la Bourse",
        "rent": 22,
        "house_1": 110,
        "house_2": 330,
        "house_3": 800,
        "house_4": 975,
        "hotel": 1150,
        "hypo": 130,
        "price": 260,
        "price_house": 150,
        "membership": [14, 15, 16],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 28,
        "idProperty": 27,
        "idFamily": 9,
        "idColor": 8,
        "type": "company",
        "imgName": "water",
        "name": "Compagnie de distribution des eaux",
        "rent": 4,
        "hypo": 75,
        "price": 150,
        "membership": [26, 27],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 29,
        "idProperty": 16,
        "idFamily": 5,
        "idColor": 5,
        "type": "property",
        "name": "Rue de la Fayette",
        "rent": 24,
        "house_1": 120,
        "house_2": 360,
        "house_3": 850,
        "house_4": 1025,
        "hotel": 1200,
        "hypo": 140,
        "price": 280,
        "price_house": 150,
        "membership": [14, 15, 16],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 30,
        "idColor": 9,
        "imgName": "goToJail",
        "name": "Allez en prison",
        "type": "other",
    },
    {
        "id": 31,
        "idProperty": 17,
        "idFamily": 6,
        "idColor": 6,
        "type": "property",
        "name": "Avenue Breteil",
        "rent": 26,
        "house_1": 130,
        "house_2": 390,
        "house_3": 900,
        "house_4": 1100,
        "hotel": 1275,
        "hypo": 150,
        "price": 300,
        "price_house": 200,
        "membership": [17, 18, 19],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 32,
        "idProperty": 18,
        "idFamily": 6,
        "idColor": 6,
        "type": "property",
        "name": "Avenue Foch",
        "rent": 26,
        "house_1": 130,
        "house_2": 390,
        "house_3": 900,
        "house_4": 1100,
        "hotel": 1275,
        "hypo": 150,
        "price": 300,
        "price_house": 200,
        "membership": [17, 18, 19],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 33,
        "idColor": 9,
        "name": "Caisse de communaute",
        "imgName": "communityChest",
        "type": "communityChest",
    },
    {
        "id": 34,
        "idProperty": 19,
        "idFamily": 6,
        "idColor": 6,
        "type": "property",
        "name": "Boulevard des Capucines",
        "rent": 28,
        "house_1": 150,
        "house_2": 450,
        "house_3": 1000,
        "house_4": 1200,
        "hotel": 1400,
        "hypo": 160,
        "price": 320,
        "price_house": 200,
        "membership": [17, 18, 19],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 35,
        "idProperty": 25,
        "idFamily": 8,
        "idColor": 8,
        "type": "station",
        "name": "Gare Saint-Lazare",
        "imgName": "station",
        "rent": 50,
        "hypo": 100,
        "price": 200,
        "membership": [22, 23, 24, 25],
        "owned": False,
        "mortgaged": False,
    },
    {"id": 36, "idColor": 9, "name": "Chance", "imgName": "chance", "type": "chance",},
    {
        "id": 37,
        "idProperty": 20,
        "idFamily": 7,
        "idColor": 7,
        "type": "property",
        "name": "Avenue des Champs-Elysées",
        "rent": 35,
        "house_1": 175,
        "house_2": 500,
        "house_3": 1100,
        "house_4": 1300,
        "hotel": 1500,
        "hypo": 175,
        "price": 350,
        "price_house": 200,
        "membership": [20, 21],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 38,
        "idColor": 9,
        "name": "Taxe de luxe",
        "imgName": "luxury",
        "type": "tax",
        "price": 100,
    },
    {
        "id": 39,
        "idProperty": 21,
        "idFamily": 7,
        "idColor": 7,
        "type": "property",
        "name": "Rue de la Paix",
        "rent": 50,
        "house_1": 200,
        "house_2": 600,
        "house_3": 1400,
        "house_4": 1700,
        "hotel": 2000,
        "hypo": 200,
        "price": 400,
        "price_house": 200,
        "membership": [20, 21],
        "owned": False,
        "mortgaged": False,
    },
]
