cases = [
    {
        "id": 0,
        "idColor": 1,
        "imgName": "start",
        "type": "start",
        "name": "Case depart",
    },
    {
        "id": 1,
        "idColor": 0,
        "type": "property",
        "name": "Boulevard de Belleville",
        "rent": 2,
        "house_1": 10,
        "house_2": 30,
        "house_3": 90,
        "house_4": 160,
        "hotel": 250,
        "mortgagePrice": 30,
        "price": 60,
        "housePrice": 50,
        "membership": [1, 3],
        "owned": False,
        "mortgaged": False,
        "built": 0,
    },
    {
        "id": 2,
        "idColor": 9,
        "name": "Caisse de communaute",
        "imgName": "communityChest",
        "type": "communityChest",
    },
    {
        "id": 3,
        "idColor": 0,
        "type": "property",
        "name": "Rue Lecourbe",
        "rent": 4,
        "house_1": 20,
        "house_2": 60,
        "house_3": 180,
        "house_4": 320,
        "hotel": 450,
        "mortgagePrice": 30,
        "price": 60,
        "housePrice": 50,
        "membership": [1, 3],
        "owned": False,
        "mortgaged": False,
        "built": 0,
    },
    {
        "id": 4,
        "idColor": 9,
        "name": "Impot sur le revenu",
        "imgName": "impot",
        "type": "tax",
        "price": 200,
    },
    {
        "id": 5,
        "idColor": 8,
        "imgName": "station",
        "type": "station",
        "name": "Gare Montparnasse",
        "rent": 50,
        "mortgagePrice": 100,
        "price": 200,
        "membership": [5, 15, 25, 35],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 6,
        "idColor": 1,
        "type": "property",
        "name": "Rue Vaugirard",
        "rent": 6,
        "house_1": 30,
        "house_2": 90,
        "house_3": 270,
        "house_4": 400,
        "hotel": 550,
        "mortgagePrice": 50,
        "price": 100,
        "housePrice": 50,
        "membership": [6, 8, 9],
        "owned": False,
        "mortgaged": False,
        "built": 0,
    },
    {"id": 7, "idColor": 9, "name": "Chance", "imgName": "chance", "type": "chance",},
    {
        "id": 8,
        "idColor": 1,
        "type": "property",
        "name": "Rue de Courcelles",
        "rent": 6,
        "house_1": 30,
        "house_2": 90,
        "house_3": 270,
        "house_4": 400,
        "hotel": 550,
        "mortgagePrice": 50,
        "price": 100,
        "housePrice": 50,
        "membership": [6, 8, 9],
        "owned": False,
        "mortgaged": False,
        "built": 0,
    },
    {
        "id": 9,
        "idColor": 1,
        "type": "property",
        "name": "Avenue de la République",
        "rent": 8,
        "house_1": 40,
        "house_2": 100,
        "house_3": 300,
        "house_4": 450,
        "hotel": 600,
        "mortgagePrice": 60,
        "price": 120,
        "housePrice": 50,
        "membership": [6, 8, 9],
        "owned": False,
        "mortgaged": False,
        "built": 0,
    },
    {
        "id": 10,
        "idColor": 9,
        "name": "Simple Visite",
        "namebis": "Prison",
        "imgName": "inJail",
        "type": "visite",
    },
    {
        "id": 11,
        "idColor": 2,
        "type": "property",
        "name": "Boulevard de la Villette",
        "rent": 10,
        "house_1": 50,
        "house_2": 150,
        "house_3": 450,
        "house_4": 625,
        "hotel": 750,
        "mortgagePrice": 70,
        "price": 140,
        "housePrice": 100,
        "membership": [11, 13, 14],
        "owned": False,
        "mortgaged": False,
        "built": 0,
    },
    {
        "id": 12,
        "idColor": 8,
        "type": "company",
        "imgName": "electricity",
        "name": "Compagnie de distribution d'electricité",
        "rent": 4,
        "mortgagePrice": 75,
        "price": 150,
        "membership": [12, 28],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 13,
        "idColor": 2,
        "type": "property",
        "name": "Avenue de Neuilly",
        "rent": 10,
        "house_1": 50,
        "house_2": 150,
        "house_3": 450,
        "house_4": 625,
        "hotel": 750,
        "mortgagePrice": 70,
        "price": 140,
        "housePrice": 100,
        "membership": [11, 13, 14],
        "owned": False,
        "mortgaged": False,
        "built": 0,
    },
    {
        "id": 14,
        "idColor": 2,
        "type": "property",
        "name": "Rue de Paradis",
        "rent": 12,
        "house_1": 60,
        "house_2": 180,
        "house_3": 500,
        "house_4": 700,
        "hotel": 900,
        "mortgagePrice": 80,
        "price": 160,
        "housePrice": 100,
        "membership": [11, 13, 14],
        "owned": False,
        "mortgaged": False,
        "built": 0,
    },
    {
        "id": 15,
        "idColor": 8,
        "type": "station",
        "imgName": "station",
        "name": "Gare de Lyon",
        "rent": 50,
        "mortgagePrice": 100,
        "price": 200,
        "membership": [5, 15, 25, 35],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 16,
        "idColor": 3,
        "type": "property",
        "name": "Avenue Mozart",
        "rent": 14,
        "house_1": 70,
        "house_2": 200,
        "house_3": 550,
        "house_4": 750,
        "hotel": 950,
        "mortgagePrice": 90,
        "price": 180,
        "housePrice": 100,
        "membership": [16, 18, 19],
        "owned": False,
        "mortgaged": False,
        "built": 0,
    },
    {
        "id": 17,
        "idColor": 9,
        "name": "Caisse de communaute",
        "imgName": "communityChest",
        "type": "communityChest",
    },
    {
        "id": 18,
        "idColor": 3,
        "type": "property",
        "name": "Boulevard Saint-Michel",
        "rent": 14,
        "house_1": 70,
        "house_2": 200,
        "house_3": 550,
        "house_4": 750,
        "hotel": 950,
        "mortgagePrice": 90,
        "price": 180,
        "housePrice": 100,
        "membership": [16, 18, 19],
        "owned": False,
        "mortgaged": False,
        "built": 0,
    },
    {
        "id": 19,
        "idColor": 3,
        "type": "property",
        "name": "Place Pigalle",
        "rent": 16,
        "house_1": 80,
        "house_2": 220,
        "house_3": 600,
        "house_4": 800,
        "hotel": 1000,
        "mortgagePrice": 100,
        "price": 200,
        "membership": [16, 18, 19],
        "owned": False,
        "mortgaged": False,
        "built": 0,
    },
    {
        "id": 20,
        "idColor": 9,
        "imgName": "freeParking",
        "type": "parc",
        "name": "Parc gratuit",
    },
    {
        "id": 21,
        "idColor": 4,
        "type": "property",
        "name": "Avenue Matignon",
        "rent": 18,
        "house_1": 90,
        "house_2": 250,
        "house_3": 700,
        "house_4": 875,
        "hotel": 1050,
        "mortgagePrice": 110,
        "price": 220,
        "housePrice": 150,
        "membership": [21, 23, 24],
        "owned": False,
        "mortgaged": False,
        "built": 0,
    },
    {"id": 22, "idColor": 9, "name": "Chance", "imgName": "chance", "type": "chance",},
    {
        "id": 23,
        "idColor": 4,
        "type": "property",
        "name": "Boulevard Malesherbes",
        "rent": 18,
        "house_1": 90,
        "house_2": 250,
        "house_3": 700,
        "house_4": 875,
        "hotel": 1050,
        "mortgagePrice": 110,
        "price": 220,
        "housePrice": 150,
        "membership": [21, 23, 24],
        "owned": False,
        "mortgaged": False,
        "built": 0,
    },
    {
        "id": 24,
        "idColor": 4,
        "type": "property",
        "name": "Avenue Henri-Martin",
        "rent": 20,
        "house_1": 100,
        "house_2": 300,
        "house_3": 750,
        "house_4": 925,
        "hotel": 1100,
        "mortgagePrice": 120,
        "price": 240,
        "housePrice": 150,
        "membership": [21, 23, 24],
        "owned": False,
        "mortgaged": False,
        "built": 0,
    },
    {
        "id": 25,
        "idColor": 8,
        "type": "station",
        "name": "Gare du Nord",
        "imgName": "station",
        "rent": 50,
        "mortgagePrice": 100,
        "price": 200,
        "membership": [5, 15, 25, 35],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 26,
        "idColor": 5,
        "type": "property",
        "name": "Faubourg Saint-Honoré",
        "rent": 22,
        "house_1": 110,
        "house_2": 330,
        "house_3": 800,
        "house_4": 975,
        "hotel": 1150,
        "mortgagePrice": 130,
        "price": 260,
        "housePrice": 150,
        "membership": [26, 27, 29],
        "owned": False,
        "mortgaged": False,
        "built": 0,
    },
    {
        "id": 27,
        "idColor": 5,
        "type": "property",
        "name": "Place de la Bourse",
        "rent": 22,
        "house_1": 110,
        "house_2": 330,
        "house_3": 800,
        "house_4": 975,
        "hotel": 1150,
        "mortgagePrice": 130,
        "price": 260,
        "housePrice": 150,
        "membership": [26, 27, 29],
        "owned": False,
        "mortgaged": False,
        "built": 0,
    },
    {
        "id": 28,
        "idColor": 8,
        "type": "company",
        "imgName": "water",
        "name": "Compagnie de distribution des eaux",
        "rent": 4,
        "mortgagePrice": 75,
        "price": 150,
        "membership": [12, 28],
        "owned": False,
        "mortgaged": False,
    },
    {
        "id": 29,
        "idColor": 5,
        "type": "property",
        "name": "Rue de la Fayette",
        "rent": 24,
        "house_1": 120,
        "house_2": 360,
        "house_3": 850,
        "house_4": 1025,
        "hotel": 1200,
        "mortgagePrice": 140,
        "price": 280,
        "housePrice": 150,
        "membership": [26, 27, 29],
        "owned": False,
        "mortgaged": False,
        "built": 0,
    },
    {
        "id": 30,
        "idColor": 9,
        "imgName": "goToJail",
        "name": "Allez en prison",
        "type": "goToJail",
    },
    {
        "id": 31,
        "idColor": 6,
        "type": "property",
        "name": "Avenue Breteil",
        "rent": 26,
        "house_1": 130,
        "house_2": 390,
        "house_3": 900,
        "house_4": 1100,
        "hotel": 1275,
        "mortgagePrice": 150,
        "price": 300,
        "housePrice": 200,
        "membership": [31, 32, 34],
        "owned": False,
        "mortgaged": False,
        "built": 0,
    },
    {
        "id": 32,
        "idColor": 6,
        "type": "property",
        "name": "Avenue Foch",
        "rent": 26,
        "house_1": 130,
        "house_2": 390,
        "house_3": 900,
        "house_4": 1100,
        "hotel": 1275,
        "mortgagePrice": 150,
        "price": 300,
        "housePrice": 200,
        "membership": [31, 32, 34],
        "owned": False,
        "mortgaged": False,
        "built": 0,
    },
    {
        "id": 33,
        "idColor": 9,
        "name": "Caisse de communaute",
        "imgName": "communityChest",
        "type": "communityChest",
    },
    {
        "id": 34,
        "idColor": 6,
        "type": "property",
        "name": "Boulevard des Capucines",
        "rent": 28,
        "house_1": 150,
        "house_2": 450,
        "house_3": 1000,
        "house_4": 1200,
        "hotel": 1400,
        "mortgagePrice": 160,
        "price": 320,
        "housePrice": 200,
        "membership": [31, 32, 34],
        "owned": False,
        "mortgaged": False,
        "built": 0,
    },
    {
        "id": 35,
        "idColor": 8,
        "type": "station",
        "name": "Gare Saint-Lazare",
        "imgName": "station",
        "rent": 50,
        "mortgagePrice": 100,
        "price": 200,
        "membership": [5, 15, 25, 35],
        "owned": False,
        "mortgaged": False,
    },
    {"id": 36, "idColor": 9, "name": "Chance", "imgName": "chance", "type": "chance",},
    {
        "id": 37,
        "idColor": 7,
        "type": "property",
        "name": "Avenue des Champs-Elysées",
        "rent": 35,
        "house_1": 175,
        "house_2": 500,
        "house_3": 1100,
        "house_4": 1300,
        "hotel": 1500,
        "mortgagePrice": 175,
        "price": 350,
        "housePrice": 200,
        "membership": [37, 39],
        "owned": False,
        "mortgaged": False,
        "built": 0,
    },
    {
        "id": 38,
        "idColor": 9,
        "name": "Taxe de luxe",
        "imgName": "luxury",
        "type": "tax",
        "price": 100,
    },
    {
        "id": 39,
        "idColor": 7,
        "type": "property",
        "name": "Rue de la Paix",
        "rent": 50,
        "house_1": 200,
        "house_2": 600,
        "house_3": 1400,
        "house_4": 1700,
        "hotel": 2000,
        "mortgagePrice": 200,
        "price": 400,
        "housePrice": 200,
        "membership": [37, 39],
        "owned": False,
        "mortgaged": False,
        "built": 0,
    },
]

model = [
    i["membership"]
    for i in sorted(cases, key=lambda x: ord(x["type"][0]))
    if "membership" in i.keys() and i["membership"][0] == i["id"]
]
