namePlayer = lambda x: f"Joueur {x}"
tour = lambda x: f"Au tour du {x}"
welcome = "Bienvenue dans le jeu MONOPOLY !"
askNumberOfPlayers = "Combien y a-t-il de joueurs ? (2, 3 ou 4) : "
diceSentence = 'Vous avez fait'
buySentence = 'Vous avez achetez'
locationSentence = 'Emplacement :'
mortgageSentence = 'Vous avez hypothequez'
unMortgageSentence = 'Vous avez dehypothequez'
buy = 'Acheter'
notBuy = 'Ne pas acheter'
lost = 'Vous avez perdu'
win = 'Vous avez gagne'
wait = 'Attendre'
getFree = 'Sortir de prison pour 50 €'